services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=devops_db
      - DB_USER=devops
      - DB_PASSWORD=secret123
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=devops_db
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=secret123
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
